import pygame

EVENT_CHANGEVIEW = pygame.USEREVENT + 0
EVENT_MUSIC = pygame.USEREVENT + 1
EVENT_MUSIC_ENDED = pygame.USEREVENT +2
EVENT_NOISE = pygame.USEREVENT + 3
EVENT_KEYJOYSTICK = pygame.USEREVENT + 4


