# -*- mode: python -*-

block_cipher = None
added_files = [
('..\\Assets\\Controls\\Gameover\\game_over.png', 'Assets\\Controls\\Gameover'),
('..\\Assets\\Controls\\Gameover\\Game_over.pyxel', 'Assets\\Controls\\Gameover'),
('..\\Assets\\Controls\\Gameover\\game_over2.png', 'Assets\\Controls\\Gameover'),
('..\\Assets\\Controls\\Gameover\\Game_over_animation.png', 'Assets\\Controls\\Gameover'),
('..\\Assets\\Controls\\StartMenue\\Credits.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Exit.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Optionen.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Pfeil.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Pfeil.pyxel', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Resume.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Start.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Controls\\StartMenue\\Titel.png', 'Assets\\Controls\\StartMenue'),
('..\\Assets\\Fonts\\InknutAntiqua-Light.ttf', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\Maximum-Security.zip', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\MAXIMUMSECURITY2.ttf', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\passion-one.zip', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\PassionOne-Regular.otf', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\PassionOne-Regular.ttf', 'Assets\\Fonts'),
('..\\Assets\\Fonts\\readme.txt', 'Assets\\Fonts'),
('..\\Assets\\Images\\dog.ico', 'Assets\\Images'),
('..\\Assets\\Images\\dog.png', 'Assets\\Images'),
('..\\Assets\\Images\\gameOver.png', 'Assets\\Images'),
('..\\Assets\\Images\\readme.txt', 'Assets\\Images'),
('..\\Assets\\Sound\\146725__fins__laser.wav', 'Assets\\Sound'),
('..\\Assets\\Sound\\172205__fins__jumping.wav', 'Assets\\Sound'),
('..\\Assets\\Sound\\173859__jivatma07__j1game-over-mono.wav', 'Assets\\Sound'),
('..\\Assets\\Sound\\319200__18hiltc__pixel-game-beep.wav', 'Assets\\Sound'),
('..\\Assets\\Sound\\flohwalzer_60_sec_0100_demo.mp3', 'Assets\\Sound'),
('..\\Assets\\Sound\\GameLost.mp3', 'Assets\\Sound'),
('..\\Assets\\Sound\\m4rt3z_m4rt3z---Elemental-Energy-Oxy-320.mp3', 'Assets\\Sound'),
('..\\Assets\\Sound\\m4rt3z_m4rt3z---Primal-Snap-320.mp3', 'Assets\\Sound'),
('..\\Assets\\Sound\\readme.txt', 'Assets\\Sound'),
('..\\Assets\\Sprites\\Bloob\\bloob.pyxel', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue.pyxel', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_gehen_links.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_gehen_rechts.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_links_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_rechts_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_springen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_blue_sterben.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_fallen_links.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_fallen_rechts.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_gehen_links.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_gehen_rechts.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_links_und_mitte.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_rechts_und_mitte.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red.pyxel', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_gehen_links.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_gehen_rechts.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_links_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_rechts_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_springen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_red_sterben.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_springen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\Bloob_sterben.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow.pyxel', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_gehen_links.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_gehen_rechts.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_links_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_rechts_drehen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_springen.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Bloob\\bloob_yellow_sterben.png', 'Assets\\Sprites\\Bloob'),
('..\\Assets\\Sprites\\Coin\\Coin.pyxel', 'Assets\\Sprites\\Coin'),
('..\\Assets\\Sprites\\Coin\\Coin_Ani.png', 'Assets\\Sprites\\Coin'),
('..\\Assets\\Sprites\\Commander\\commander_standing_front.png', 'Assets\\Sprites\\Commander'),
('..\\Assets\\Sprites\\Commander\\commander_walk_left.png', 'Assets\\Sprites\\Commander'),
('..\\Assets\\Sprites\\Commander\\commander_walk_right.png', 'Assets\\Sprites\\Commander'),
('..\\Assets\\Sprites\\Drawbridge\\Drawbridge_Ani.png', 'Assets\\Sprites\\Drawbridge'),
('..\\Assets\\Sprites\\Drawbridge\\Falltor_zu.png', 'Assets\\Sprites\\Drawbridge'),
('..\\Assets\\Sprites\\Drawbridge\\Stahlwand_auf.png', 'Assets\\Sprites\\Drawbridge'),
('..\\Assets\\Sprites\\Drawbridge\\Stahlwand_zu.png', 'Assets\\Sprites\\Drawbridge'),
('..\\Assets\\Sprites\\Drawbridge\\Türen.pyxel', 'Assets\\Sprites\\Drawbridge'),
('..\\Assets\\Sprites\\Heart\\heart.pyxel', 'Assets\\Sprites\\Heart'),
('..\\Assets\\Sprites\\Heart\\Heart_Ani.png', 'Assets\\Sprites\\Heart'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo.pyxel', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo_jump_left.png', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo_jump_right.png', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo_Left.png', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo_Right.png', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\Jimbo\\Jimbo_standing.png', 'Assets\\Sprites\\Jimbo'),
('..\\Assets\\Sprites\\John_Doe\\climb.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\John_Doe_springen.pyxel', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\jubeln.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\jump_left.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\jump_right.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\jump_up.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\New_Man_in_Town.pyxel', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\standing_front.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\standing_left.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\standing_right.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\tot.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\walk_left.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\John_Doe\\walk_right.png', 'Assets\\Sprites\\John_Doe'),
('..\\Assets\\Sprites\\LifeLostMessage\\graveStone.png', 'Assets\\Sprites\\LifeLostMessage'),
('..\\Assets\\Sprites\\LifeLostMessage\\LifeLostMessage.png', 'Assets\\Sprites\\LifeLostMessage'),
('..\\Assets\\Sprites\\Monster_Bloob\\MonsterBloob.pyxel', 'Assets\\Sprites\\Monster_Bloob'),
('..\\Assets\\Sprites\\Monster_Bloob\\MonsterBloob_green_die.png', 'Assets\\Sprites\\Monster_Bloob'),
('..\\Assets\\Sprites\\Monster_Bloob\\MonsterBloob_green_walk_left.png', 'Assets\\Sprites\\Monster_Bloob'),
('..\\Assets\\Sprites\\Monster_Bloob\\MonsterBloob_green_walk_right.png', 'Assets\\Sprites\\Monster_Bloob'),
('..\\Assets\\Sprites\\Optionen\\Optionen.png', 'Assets\\Sprites\\Optionen'),
('..\\Assets\\Sprites\\Private\\privat_standing_front.png', 'Assets\\Sprites\\Private'),
('..\\Assets\\Sprites\\Private\\privat_walk_left.png', 'Assets\\Sprites\\Private'),
('..\\Assets\\Sprites\\Private\\privat_walk_right.png', 'Assets\\Sprites\\Private'),
('..\\Assets\\Sprites\\StartMenue\\Credits.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\DemoStartButtons.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\Exit.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\Optionen.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\Resume.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\Start.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\StartMenue\\Titel.png', 'Assets\\Sprites\\StartMenue'),
('..\\Assets\\Sprites\\Targedpoint\\Flagge1.png', 'Assets\\Sprites\\Targedpoint'),
('..\\Assets\\Sprites\\Targedpoint\\Flagge2.png', 'Assets\\Sprites\\Targedpoint'),
('..\\Assets\\Sprites\\Targedpoint\\Flagge3.png', 'Assets\\Sprites\\Targedpoint'),
('..\\Assets\\Sprites\\Targedpoint\\Flagge4.png', 'Assets\\Sprites\\Targedpoint'),
('..\\Assets\\Sprites\\Targedpoint\\Flagge5.png', 'Assets\\Sprites\\Targedpoint'),
('..\\Assets\\Sprites\\Teleporter\\Teleporter_Back.png', 'Assets\\Sprites\\Teleporter'),
('..\\Assets\\Sprites\\Teleporter\\Teleporter_Front.png', 'Assets\\Sprites\\Teleporter'),
('..\\Assets\\Sprites\\Teleporter\\Telepunkt.png', 'Assets\\Sprites\\Teleporter'),
('..\\Assets\\Views\\Demo\\demo.png', 'Assets\\Views\\Demo'),
('..\\Assets\\Views\\Demo\\demo.tmx', 'Assets\\Views\\Demo'),
('..\\Assets\\Views\\Demo\\Demobackground.png', 'Assets\\Views\\Demo'),
('..\\Assets\\Views\\Demo\\map.json', 'Assets\\Views\\Demo'),
('..\\Assets\\Views\\DemoFinal\\demo.png', 'Assets\\Views\\DemoFinal'),
('..\\Assets\\Views\\DemoFinal\\DemoFinal.tmx', 'Assets\\Views\\DemoFinal'),
('..\\Assets\\Views\\DemoFinal\\DemoFinalbackground.png', 'Assets\\Views\\DemoFinal'),
('..\\Assets\\Views\\DemoFinal\\map.json', 'Assets\\Views\\DemoFinal'),
('..\\Assets\\Views\\DemoOptions\\map.json', 'Assets\\Views\\DemoOptions'),
('..\\Assets\\Views\\DemoOptions\\Options.tmx', 'Assets\\Views\\DemoOptions'),
('..\\Assets\\Views\\DemoStart\\demo.png', 'Assets\\Views\\DemoStart'),
('..\\Assets\\Views\\DemoStart\\Demobackground.png', 'Assets\\Views\\DemoStart'),
('..\\Assets\\Views\\DemoStart\\Demobackground2.png', 'Assets\\Views\\DemoStart'),
('..\\Assets\\Views\\DemoStart\\DemoStart.tmx', 'Assets\\Views\\DemoStart'),
('..\\Assets\\Views\\DemoStart\\map.json', 'Assets\\Views\\DemoStart'),
('..\\Assets\\Views\\GameLost\\gamelost.tmx', 'Assets\\Views\\GameLost'),
('..\\Assets\\Views\\GameLost\\map.json', 'Assets\\Views\\GameLost'),
('..\\Assets\\Views\\Level1\\background.png', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\background.png.old', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\background3.png', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\Level1.png', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\Level1.pyxel', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\Level1.tmx', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level1\\map.json', 'Assets\\Views\\Level1'),
('..\\Assets\\Views\\Level2\\background6.png', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\Level2.png', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\Level2.pyxel', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\Level2.tmx', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\map.json', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\MonsterBloob_green_die.png', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level2\\view.map', 'Assets\\Views\\Level2'),
('..\\Assets\\Views\\Level3\\Level3.png', 'Assets\\Views\\Level3'),
('..\\Assets\\Views\\Level3\\Level3.tmx', 'Assets\\Views\\Level3'),
('..\\Assets\\Views\\Level3\\map.json', 'Assets\\Views\\Level3'),
('..\\Assets\\Views\\Training\\background3.png', 'Assets\\Views\\Training'),
('..\\Assets\\Views\\Training\\map.json', 'Assets\\Views\\Training'),
('..\\Assets\\Views\\Training\\training.png', 'Assets\\Views\\Training'),
('..\\Assets\\Views\\Training\\training.tmx', 'Assets\\Views\\Training')
]

a = Analysis(['..\\Src\\Game.py'],
             pathex=['.\\'],
             binaries=None,
             datas=added_files,
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             win_no_prefer_redirects=None,
             win_private_assemblies=None,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='Game',
          debug=False,
          strip=None,
          upx=True,
          console=False , icon='..\\Assets\\Images\\dog.ico')
